-- 日付らしい列の型・長さの集計（yyyymmdd 文字列の運用の確認）
SELECT DATA_TYPE, CHARACTER_MAXIMUM_LENGTH AS len, COUNT(*) AS cnt
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = @schema
  AND (DATA_TYPE IN ('date', 'datetime', 'datetime2', 'smalldatetime')
       OR COLUMN_NAME LIKE '%YMD%' OR COLUMN_NAME LIKE '%DATE%'
       OR COLUMN_NAME LIKE '%DT%' OR COLUMN_NAME LIKE N'%日%')
GROUP BY DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
ORDER BY cnt DESC;

-- 明細
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH AS len, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = @schema
  AND (DATA_TYPE IN ('date', 'datetime', 'datetime2', 'smalldatetime')
       OR COLUMN_NAME LIKE '%YMD%' OR COLUMN_NAME LIKE '%DATE%'
       OR COLUMN_NAME LIKE '%DT%' OR COLUMN_NAME LIKE N'%日%')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
