-- 主キーの列数ごとのテーブル数（複合主キーの多さ）
SELECT key_cols, COUNT(*) AS tables
FROM (
  SELECT tc.TABLE_NAME, COUNT(*) AS key_cols
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
  JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
   AND kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA
   AND kcu.TABLE_NAME = tc.TABLE_NAME
  WHERE tc.TABLE_SCHEMA = @schema AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
  GROUP BY tc.TABLE_NAME
) x
GROUP BY key_cols
ORDER BY key_cols;

-- 主キーのないテーブル（キー列の手動指定が必要になるもの）
SELECT t.TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES t
WHERE t.TABLE_SCHEMA = @schema
  AND t.TABLE_TYPE = 'BASE TABLE'
  AND NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE tc.TABLE_SCHEMA = t.TABLE_SCHEMA AND tc.TABLE_NAME = t.TABLE_NAME
      AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
  )
ORDER BY t.TABLE_NAME;

-- 外部キーの数（念のため。0件の想定）
SELECT COUNT(*) AS fk_count
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = @schema AND CONSTRAINT_TYPE = 'FOREIGN KEY';
