-- 確かめる用の架空の表（Oracle）。社内のテーブルとは関係ない。README の手順で APP_USER のスキーマに作る
CREATE TABLE ORDERS (ORDER_NO VARCHAR2(10) PRIMARY KEY, ORDER_YMD VARCHAR2(8), QTY NUMBER(10), CUST_CD VARCHAR2(6));
CREATE TABLE CUSTOMERS (CUST_CD VARCHAR2(6) PRIMARY KEY, CUST_NAME VARCHAR2(80), PREF VARCHAR2(20));
CREATE VIEW V_ORDERS AS SELECT ORDER_NO, QTY FROM ORDERS;
-- 論理名（D-40）：COMMENT ON。「:」の前が論理名、後ろは説明。改行の後ろも説明
COMMENT ON TABLE ORDERS IS '受注明細:受注 1 件の明細';
COMMENT ON COLUMN ORDERS.ORDER_NO IS '受注番号';
COMMENT ON COLUMN ORDERS.ORDER_YMD IS '受注日
yyyymmdd';
COMMENT ON COLUMN ORDERS.QTY IS '数量';
COMMENT ON TABLE CUSTOMERS IS '得意先';
COMMENT ON COLUMN CUSTOMERS.CUST_NAME IS '得意先名';
COMMENT ON TABLE V_ORDERS IS '未完了の受注';
INSERT INTO CUSTOMERS VALUES ('C00001', '山田商店', '東京都');
INSERT INTO CUSTOMERS VALUES ('C00002', '佐藤工業', '大阪府');
INSERT INTO ORDERS VALUES ('D001', '20260901', 5, 'C00001');
INSERT INTO ORDERS VALUES ('D002', '20260902', 7, 'C00002');
COMMIT;
EXIT
